### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [elementlo/spark_list#1]
请问是否可以将应用发布到 F-Droid？谢谢！

**Comment by elementlo** [comment]
> 

多谢建议， 我试试吧，进度也更新在这里。

**Comment by elementlo** [comment]
> 请问是否可以将应用发布到 F-Droid？谢谢！

多谢建议， 我试试吧，进度也更新在这里。

**Comment by linsui** [comment]
谢谢！

**Comment by elementlo** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2017
提交了打包申请，进度可以跟踪这个issue，等一些规范问题改完应该就可以上了，预计一周左右。

**Comment by linsui** [comment]
谢谢！

**Comment by elementlo** [comment]
已经上架F-Droid了。
过程很坎坷了，有兴趣的可以看上面那个issue.

目前已知问题：
英文版本下，归档页的标题拼写错了，点击归档页的清除按钮，对话框的文本还没有适配英文。目前在完成联动Notion的开发，会一并解决这两个问题。

Already in F-Droid now, search Shorey to install it:)


![WechatIMG188](https://user-images.githubusercontent.com/10020581/156323201-144192b3-bcbb-4044-be21-0e3e9528a486.jpeg)

**Comment by linsui** [comment]
非常感谢！

**Comment by linsui** [comment]
这个是 F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.elementlo.spark_list/)

```md
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.elementlo.spark_list)
```
